#!/bin/sh
# Exercise bugs whereby invalid input could make gzip -d misbehave.

# Copyright (C) 2009-2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

printf '\n...: invalid compressed data--format violated\n' > exp \
  || framework_failure_

fail=0
returns_ 1 gzip -dc "$abs_srcdir/hufts-segv.gz" > out 2> err-raw || fail=1

compare /dev/null out || fail=1

# sed script to remove hard-to-compare stderr fluff, including shell
# debugging output and full file-names.
clean_stderr='
  s/.*hufts-segv.gz: /...: /
  /^+/d
  /Operation-Ending-Supplemental Code/d
'

sed "$clean_stderr" err-raw > err || framework_failure_
compare exp err || fail=1

printf '\037\213\010\000\060\060\060\060\060\060\144\000\000\000' > bug33501 \
  || framework_failure_
printf '\ngzip: stdin: invalid compressed data--format violated\n' >exp33501 \
  || framework_failure_
returns_ 1 gzip -d <bug33501 >out33501 2> err33501-raw || fail=1
sed "$clean_stderr" err33501-raw > err33501 || framework_failure_
compare exp33501 err33501 || fail=1

Exit $fail
