#!/bin/sh
# Exercise the --list option with a big file.

# Copyright 2021-2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

dd bs=65536 seek=65536 if=/dev/null of=big || framework_failure_

gzip -1 big || fail=1
gzip -l big.gz >out || fail=1
case $(cat out) in
  *' 4294967296 '*' big') ;;
  *) cat out; fail=1;;
esac

Exit $fail
