#!/bin/sh
# Ensure that gzip can compress more than one file.

# Copyright 2020-2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

test -r /dev/urandom || skip_ "/dev/urandom missing"

dd if=/dev/urandom of=a count=5000 bs=1
dd if=/dev/urandom of=b count=5000 bs=1
cp a a.exp
cp b b.exp
gzip -1 a b || fail=1
gzip -d a.gz b.gz || fail=1
compare a.exp a || fail=1
compare b.exp b || fail=1

Exit $fail
