#!/bin/sh
# Test for improved diagnostics

# Copyright 2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

fail=0

mkdir d || framework_failure_
echo > d/f || framework_failure_
chmod a-w d || framework_failure_
if test -w d; then
  echo >&2 "$0: being root, skipping this test"
  fail=77
else
  returns_ 1 gzip d/f > out 2> err || fail=1
fi

Exit $fail
