#!/bin/sh
# 'zgrep PATTERN FILE' would output "(standard input): binary file matches"
# without mentioning FILE.  Fixed in gzip-1.12.

# Copyright (C) 2022-2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

fail=0

unset GREP_OPTIONS

printf 'foo\0\n' >f || framework_failure_
LC_ALL=C zgrep foo f >out 2>err && grep '(standard input)' out err && fail=1

Exit $fail
