#!/bin/sh
# Show how zgrep applied to a crafted file name may overwrite
# a selected file with chosen content.  Fixed in gzip-1.12.

# Copyright (C) 2022-2023 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

: > z || framework_failure_
echo test |gzip > 'z|
p
1s|.*|chosen-content|
1w hacked
etouch .\x2fhacked2
d
#
#' || framework_failure_

fail=0

zgrep test z* > /dev/null

# Before the fix, each of these would be created.
test -f hacked && fail=1
test -f hacked2 && fail=1

Exit $fail
